specfile_path: colin.spec
files_to_sync:
  - colin.spec
  - .packit.yaml
upstream_package_name: colin
downstream_package_name: colin
jobs:
  - job: sync_from_downstream
    trigger: commit
  - job: propose_downstream
    trigger: release
    copy_upstream_release_description: true
    metadata:
      dist-git-branch: fedora-all
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
  # downstream Koji build
  - job: koji_build
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-all
