---
- name: Install test dependencies
  dnf:
    name:
      - python3-setuptools
      - python3-pytest
      - python3-pytest-cov
      - python3-pyxattr
      - moby-engine
      - podman
      - buildah
      - skopeo
      - runc
      - wget
    state: present
  become: true
- name: Download umoci
  command:
    cmd: wget -O /usr/local/bin/umoci "https://github.com/opencontainers/umoci/releases/download/v0.4.7/umoci.amd64"
- name: Make umoci executable
  file: dest=/usr/local/bin/umoci mode=a+x
